# Generated by Django 4.2.6 on 2023-10-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_alter_question_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(default='<empty_text>', max_length=4096),
        ),
    ]
