version: '3.9'
name: redis

services:
  redis:
    image: redis:7.2.1-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16